# \
CS 170 - Theory of Operating Systems\
By: Matthew S Montoya\
Purpose: To Practice Navigating the Linux Filesystem using C\
Last Modified: 24 April 2019

src.o: src.c
	gcc src.c src.o
	
clean:
	rm -f *.o